"""Phase-1 audit of recovery endpoint fields in retained episode-level results.

This script is intentionally read-only with respect to source protocols: it only
inspects existing CSV headers and values and writes an audit artifact.
"""

from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "results/gate1_safety_fx60_failure_timing_generalization_formal_merged/test_episode_metrics.csv"
OUT_CSV = ROOT / "results/recovery_endpoint_audit.csv"
OUT_MD = ROOT / "docs/RECOVERY_ENDPOINT_AUDIT.md"

REQUIRED_STRICT_FIELDS = (
    "pre_failure_chain_established",
    "post_failure_chain_recovered_after_loss",
    "post_failure_chain_recovery_steps",
)


def main() -> None:
    if not INPUT.exists():
        raise FileNotFoundError(INPUT)
    with INPUT.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        fields = reader.fieldnames or []

    missing = [field for field in REQUIRED_STRICT_FIELDS if field not in fields]
    groups: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[(row.get("scenario", ""), row.get("graph_encoder", ""))].append(row)

    audit_rows: list[dict[str, str]] = []
    for (scenario, method), group in sorted(groups.items()):
        def mean_flag(field: str) -> str:
            values = [float(row[field]) for row in group if row.get(field, "") not in {"", "-1"}]
            return f"{sum(values) / len(values):.6f}" if values else "NA"

        audit_rows.append(
            {
                "scenario": scenario,
                "method": method,
                "n_episodes": str(len(group)),
                "reported_post_failure_recovered_mean": mean_flag("post_failure_chain_recovered"),
                "reported_recovered_after_loss_mean": mean_flag("post_failure_chain_recovered_after_loss"),
                "reported_unrecovered_mean": mean_flag("post_failure_chain_unrecovered"),
                "strict_pre_established_field_present": str("pre_failure_chain_established" in fields),
                "strict_recovered_after_loss_field_present": str(
                    "post_failure_chain_recovered_after_loss" in fields
                ),
                "strict_recovery_cohort_reconstructable": str(not missing),
            }
        )

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(audit_rows[0]))
        writer.writeheader()
        writer.writerows(audit_rows)

    lines = [
        "# Recovery Endpoint Audit",
        "",
        "Generated by `scripts/audit_recovery_endpoint_phase1.py` from retained episode-level results.",
        "This audit is read-only and does not modify the evaluation protocol or start training.",
        "",
        "## Source",
        "",
        f"- Input: `{INPUT.relative_to(ROOT).as_posix()}`",
        f"- Episodes inspected: {len(rows)}",
        f"- Fields missing for strict cohort reconstruction: {', '.join(missing) if missing else 'none'}",
        "",
        "## Semantic finding",
        "",
        "The retained CSV exposes a reported `post_failure_chain_recovered_after_loss` field, but it does not expose `pre_failure_chain_established` in its header. Therefore the strict cohort `pre-established → post-failure loss → re-closure` cannot be reconstructed from this retained CSV alone. The reported `post_failure_chain_recovered` value must not be treated as a fully audited strict recovery endpoint.",
        "",
        "Recommended strict endpoint for future episode-level evaluation:",
        "",
        "```text",
        "pre_failure_chain_established",
        "AND chain_lost_after_failure",
        "AND post_failure_chain_recovered_after_loss",
        "```",
        "",
        "Until the required episode-level fields are recovered or a frozen re-evaluation produces them, the headline should be named `post-failure chain establishment/closure`, not strict re-establishment recovery.",
        "",
        "## Group summary",
        "",
        "| Scenario | Method | Episodes | Reported recovery | Reported after-loss | Strict cohort reconstructable |",
        "|---|---|---:|---:|---:|---|",
    ]
    for row in audit_rows:
        lines.append(
            f"| {row['scenario']} | {row['method']} | {row['n_episodes']} | {row['reported_post_failure_recovered_mean']} | {row['reported_recovered_after_loss_mean']} | {row['strict_recovery_cohort_reconstructable']} |"
        )
    lines.extend(
        [
            "",
            "## Phase-1 disposition",
            "",
            "- No training was started.",
            "- No scientific protocol was changed.",
            "- Existing retained data are sufficient for an endpoint-field inventory and partial descriptive audit.",
            "- A strict recovery cohort audit requires episode-level pre-failure chain state and explicit loss timing; these are missing from the retained CSV.",
        ]
    )
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
