"""NP1 no-training calibration for a within-episode Scout sensing loss.

This script is deliberately an adapter-level audit.  It does not train a
policy and does not modify the legacy environment.  It verifies that a
capability transition removes only lawful Scout target evidence, propagates
the changed capability through delivered sender-status packets, and compares
a frozen nominal controller with a transparent reallocated controller.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import replace
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from envs.uav_intercept_3d_env import (  # noqa: E402
    ROLE_ATTACKER,
    ROLE_SCOUT,
    UAVIntercept3DConfig,
    UAVIntercept3DEnv,
)
from scripts import run_new_project_l0_single_interceptor as l0  # noqa: E402


OUT = ROOT / "results" / "np1_dynamic_capability_calibration"
PROTOCOL = "NP1_DYNAMIC_CAPABILITY_TASK_IDENTIFIABILITY_CALIBRATION_V1"
SEEDS = (9101, 9102, 9103, 9104)
TRANSITION_STEP = 18
HORIZON = 120


class DynamicCapabilityAdapter(UAVIntercept3DEnv):
    """New-project adapter; the legacy UAVIntercept3DEnv remains untouched."""

    def __init__(self, config: UAVIntercept3DConfig, *, transition_step: int):
        super().__init__(config)
        self.transition_step = int(transition_step)
        self.scout_sensing_lost = False
        self.scout_id = next(i for i, t in enumerate(config.blue_types) if t.role == ROLE_SCOUT)

    def reset(self):
        self.scout_sensing_lost = False
        return super().reset()

    def _make_sender_status_packet(self, sender: int, send_step: int) -> dict[str, object]:
        packet = super()._make_sender_status_packet(sender, send_step)
        if self.scout_sensing_lost and int(sender) == self.scout_id:
            # Lawful self-reported capability status: no target evidence is
            # published after the local sensing capability is lost.
            packet["detected_by"] = 0.0
            packet["target_pos"] = np.zeros(3, dtype=np.float32)
            packet["target_vel"] = np.zeros(3, dtype=np.float32)
            packet["target_confidence"] = 0.0
            packet["target_generation_step"] = -1
            packet["target_hop_count"] = -1
            packet["local_attack_window"] = 0.0
        return packet

    def _invalidate_scout_evidence(self) -> None:
        s = self.scout_id
        self.detected_by[s] = 0.0
        self.local_attack_window[s] = 0.0
        self.attack_window[s] = 0.0
        self.target_cache_valid[s] = 0.0
        self.target_cache_pos[s] = 0.0
        self.target_cache_vel[s] = 0.0
        self.target_cache_source[s] = -1
        self.target_cache_generation_step[s] = -1
        self.target_cache_delivery_step[s] = -1
        self.target_cache_hop_count[s] = -1
        self.target_cache_confidence[s] = 0.0
        self.target_cache_path[s] = []
        # Remove packets whose only target evidence was generated by Scout.
        for receiver in range(self.config.num_blue):
            cached = self.sender_packet_cache[receiver].get(s)
            if cached is not None:
                cached["detected_by"] = 0.0
                cached["target_pos"] = np.zeros(3, dtype=np.float32)
                cached["target_vel"] = np.zeros(3, dtype=np.float32)
                cached["target_confidence"] = 0.0
                cached["target_generation_step"] = -1
                cached["target_hop_count"] = -1
            self.target_cache_valid[receiver] = 0.0 if int(self.target_cache_source[receiver]) == s else self.target_cache_valid[receiver]
        self.pending_target_messages = [
            m for m in self.pending_target_messages if int(m.get("sender", -1)) != s
        ]

    def _update_sensing_and_comm(self) -> None:
        super()._update_sensing_and_comm()
        if self.scout_sensing_lost:
            self._invalidate_scout_evidence()

    def step_guidance(self, guidance_actions: np.ndarray):
        """Execute [turn, climb] only; mission commit is automatic for attacker."""
        guidance = np.asarray(guidance_actions, dtype=np.float32).reshape(self.config.num_blue, 2)
        full = np.zeros((self.config.num_blue, 3), dtype=np.float32)
        full[:, :2] = np.clip(guidance, -1.0, 1.0)
        for i, typ in enumerate(self.config.blue_types):
            if typ.role == ROLE_ATTACKER:
                full[i, 2] = 1.0
        # The transition is applied to the state produced by this transition,
        # so arm it one step before the base environment increments step_count.
        if self.step_count + 1 >= self.transition_step:
            self.scout_sensing_lost = True
        return super().step(full)


def config(seed: int) -> UAVIntercept3DConfig:
    base = UAVIntercept3DConfig(
        seed=seed,
        max_steps=HORIZON,
        mission_neutralization_enabled=True,
        continuous_guidance_action_interface=True,
        strict_target_sensing=True,
        agent_target_info_bottleneck=True,
        communication_dropout_prob=0.0,
        message_delay_steps=0,
        radar_dropout_prob=0.0,
        max_target_message_age_steps=12,
        target_escape_radius=45_000.0,
        target_policy="straight",
        target_prior_position=(0.0, 0.0, 5_000.0),
        relay_identifiable_target_initial_position=(0.0, 0.0, 5_000.0),
    )
    # Scout is the nominal sensor.  Relay has a lawful but shorter backup
    # sensor range; it can become useful after moving into the target region.
    types = list(base.blue_types)
    types[0] = replace(types[0], radar_range=17_500.0)
    types[1] = replace(types[1], radar_range=9_000.0)
    types[2] = replace(types[2], radar_range=11_000.0)
    return replace(base, blue_types=types)


def scripted_guidance(env: DynamicCapabilityAdapter, obs: np.ndarray) -> np.ndarray:
    actions = np.zeros((env.config.num_blue, 2), dtype=np.float32)
    for i in range(env.config.num_blue):
        # The transparent controller only uses the recipient's current legal
        # observation.  With no target evidence it holds a neutral command.
        if float(obs[i, 11]) <= 0.0:
            continue
        legacy = l0.heuristic_action(obs[i : i + 1])[0]
        actions[i] = l0.GUIDANCE_ACTION_TABLE[int(legacy) % l0.GUIDANCE_FLIGHT_ACTION_DIM]
    return actions


def run(seed: int, mode: str) -> dict[str, object]:
    env = DynamicCapabilityAdapter(config(seed), transition_step=TRANSITION_STEP)
    obs, _, _ = env.reset()
    pre_actions: list[np.ndarray] = []
    pre_obs = obs.copy()
    before = None
    after = None
    transition_status = None
    expiry_check = None
    while not env.done and env.step_count < HORIZON:
        if mode == "nominal" and env.step_count >= TRANSITION_STEP and pre_actions:
            action = pre_actions[-1].copy()
        else:
            action = scripted_guidance(env, obs)
        if env.step_count < TRANSITION_STEP:
            pre_actions.append(action.copy())
        if env.step_count == TRANSITION_STEP - 1:
            before = {
                "step": env.step_count,
                "scout_detected": float(env.detected_by[env.scout_id]),
                "scout_has_target": bool(env._has_target_information(env.scout_id)),
            }
        obs, _, _, _, dones, info = env.step_guidance(action)
        if env.step_count == TRANSITION_STEP:
            after = {
                "step": env.step_count,
                "scout_detected": float(env.detected_by[env.scout_id]),
                "scout_has_target": bool(env._has_target_information(env.scout_id)),
                "relay_has_target": bool(env._has_target_information(1)),
            }
            relay_packet = env.sender_packet_cache[1].get(env.scout_id, {})
            transition_status = {
                "relay_received_scout_status": bool(relay_packet),
                "relay_packet_detected_by": float(relay_packet.get("detected_by", -1.0)) if relay_packet else -1.0,
                "relay_packet_target_confidence": float(relay_packet.get("target_confidence", -1.0)) if relay_packet else -1.0,
            }
        if env.step_count == TRANSITION_STEP + env.config.max_target_message_age_steps + 1:
            expiry_check = {
                "step": env.step_count,
                "relay_cache_still_stored": bool(env.target_cache_valid[1] > 0.5),
                "relay_has_fresh_target": bool(env._has_target_information(1)),
                "relay_cache_age": float(env._local_target_cache_age(1)),
            }
        if bool(dones[0, 0]):
            break
    outcome = "NEUTRALIZED" if info.get("target_neutralized", 0.0) > 0.5 else (
        "COLLISION" if info.get("collision", 0.0) > 0.5 else (
            "CONSTRAINT_FAILURE" if info.get("constraint_violation", 0.0) > 0.5 else (
                "TARGET_ESCAPE" if info.get("target_escape", 0.0) > 0.5 else "TIMEOUT"
            )
        )
    )
    return {
        "seed": seed,
        "mode": mode,
        "outcome": outcome,
        "steps": int(env.step_count),
        "before": before,
        "after": after,
        "transition_status": transition_status,
        "expiry_check": expiry_check,
        "scout_loss_applied": bool(env.scout_sensing_lost),
    }


def expiry_semantics_probe() -> dict[str, object]:
    """Deterministic check independent of whether the mission ends early."""
    env = DynamicCapabilityAdapter(config(SEEDS[0]), transition_step=TRANSITION_STEP)
    env.reset()
    env._write_target_cache(
        1,
        pos=env.red_pos[0].copy(),
        vel=np.zeros(3, dtype=np.float32),
        source=env.scout_id,
        generation_step=0,
        delivery_step=0,
        hop_count=1,
        confidence=1.0,
        path=[env.scout_id, 1],
    )
    env.step_count = env.config.max_target_message_age_steps + 1
    return {
        "cache_stored_after_expiry": bool(env.target_cache_valid[1] > 0.5),
        "fresh_target_after_expiry": bool(env._has_target_information(1)),
        "cache_age": float(env._local_target_cache_age(1)),
        "pass": bool(env.target_cache_valid[1] > 0.5 and not env._has_target_information(1)),
    }


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    nominal = [run(seed, "nominal") for seed in SEEDS]
    reallocated = [run(seed, "reallocated") for seed in SEEDS]
    transition_pass = all(
        r["before"] and r["after"]
        and r["before"]["scout_has_target"]
        and not r["after"]["scout_has_target"]
        and r["transition_status"]
        and r["transition_status"]["relay_received_scout_status"]
        and r["transition_status"]["relay_packet_detected_by"] == 0.0
        for r in reallocated
    )
    nominal_success = sum(r["outcome"] == "NEUTRALIZED" for r in nominal)
    reallocated_success = sum(r["outcome"] == "NEUTRALIZED" for r in reallocated)
    # NP1 is intentionally conservative: a transition is not enough; the
    # alternative controller must recover while the frozen nominal assignment
    # fails.  A simple per-step mask that already achieves this is not a pass.
    if transition_pass and reallocated_success > nominal_success and reallocated_success > 0:
        verdict = "NP1_PASS__RESPONSIBILITY_REALLOCATION_PROBLEM_IDENTIFIED__READY_FOR_METHOD_DESIGN"
    elif transition_pass:
        verdict = "NP1_PARTIAL__CAPABILITY_TRANSITION_VALID_BUT_REALLOCATION_NECESSITY_UNCLEAR"
    else:
        verdict = "NP1_NO_GO__DYNAMIC_CAPABILITY_PROBLEM_NOT_IDENTIFIABLE"
    report = {
        "protocol_version": PROTOCOL,
        "transition_step": TRANSITION_STEP,
        "horizon": HORIZON,
        "training": False,
        "algorithm": None,
        "nominal": nominal,
        "reallocated": reallocated,
        "nominal_neutralized": nominal_success,
        "reallocated_neutralized": reallocated_success,
        "expiry_semantics_probe": expiry_semantics_probe(),
        "transition_pass": transition_pass,
        "verdict": verdict,
    }
    (OUT / "NP1_CALIBRATION_REPORT.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (OUT / "NP1_CALIBRATION_MANIFEST.json").write_text(json.dumps({
        "protocol_version": PROTOCOL,
        "source_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
        "seeds": list(SEEDS),
        "transition_step": TRANSITION_STEP,
        "horizon": HORIZON,
        "uses_training": False,
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"{verdict}: nominal={nominal_success}/{len(SEEDS)} reallocated={reallocated_success}/{len(SEEDS)} transition_pass={transition_pass}")


if __name__ == "__main__":
    main()
